name: flutter_easy_camera
description: "EasyCamera is a Flutter plugin for seamless camera integration,
  offering customizable settings, preview styles, and intuitive controls for
  capturing images."

homepage: https://github.com/TheinvinciblePrints/easy_camera

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.3.0"
  
dependencies:
  camera: ^0.11.2
  flutter:
    sdk: flutter
  image_editor: ^1.6.0
  native_device_orientation:
    git:
      url: https://github.com/bashcious/flutter_native_device_orientation.git
      ref: master
  photo_view: ^0.15.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
